parameters:
#    chessy_web_guest_book.example.class: ChessyWeb\GuestBookBundle\Example

services:
#    chessy_web_guest_book.example:
#        class: %chessy_web_guest_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
