<?php

namespace ChessyWeb\GuestBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuestMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestMessageRepository extends EntityRepository
{
}
